---
- name: "Template custom configuration file."
  template:
    src: "rsyslog.conf.j2"
    dest: "{{ aspects_rsyslog_custom_config_file_path }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "restart rsyslog"
  tags:
    - aspects_rsyslog
    - aspects_rsyslog_config
    - aspects_rsyslog_configuration

- name: "Template separate configuration files in rsyslog.d."
  when: item.value.enabled
  template:
    src: "separate-file.conf.j2"
    dest: "/etc/rsyslog.d/{{ item.value.weight }}-{{ item.value.name }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  with_dict: "{{ aspects_rsyslog_separate_files_config|default({}) }}"
  notify: "restart rsyslog"
  tags:
    - aspects_rsyslog
    - aspects_rsyslog_config
    - aspects_rsyslog_configuration