---
- name: "install rsyslog packages"
  include: "{{ ansible_pkg_mgr}}InstallPackages.yml"
  tags:
    - aspects_rsyslog
    - aspects_rsyslog_package_install

- name: "Template custom configuration file."
  template:
    src: "rsyslog.conf.j2"
    dest: "{{ aspects_rsyslog_custom_config_file_path }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "restart rsyslog"
  tags:
    - aspects_rsyslog
    - aspects_rsyslog_config
    - aspects_rsyslog_configuration
