---
- name: yum - Install rsyslog packages on CentOS 7
  when:
    (
      ansible_distribution == "CentOS" and
      ansible_distribution_major_version == "7" and
      (
        item.value.state == "present" or
        item.value.state == "latest"
      )
    )
  yum:
    name: "{{ item.value.CentOS.7 }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ aspects_rsyslog_packages }}"
  tags:
    - aspects_rsyslog
    - aspects_rsyslog_package_install
    - aspects_rsyslog_package_install_yum
